### PR TITLE
Add drag and zoom to viewing area

### PR DESCRIPTION
**Pull request by clenk**
The mousewheel can be used to zoom in and out, and clicking and dragging on the background will move the graph around to aid in viewing large datasets.

### CODE REVIEW

**Comment by gtback** [comment]
I just realized that this conflicts with when you're trying to manually click and drag a node to move it to a specific location. (Drag should work _only_ when you click on the background)

**Comment by gtback** [comment]
Also, double-click (which is used to unpin a node) also causes the viewport to zoom in.

**Comment by b-long** [comment]
I agree with @gtback , this seems to cause a regression .  Still, the zoom feature is very nice! 👍

**Comment by clenk** [comment]
This will be fixed in #5.

**Pull request merged**
